name: picle
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.7.1+cu128
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - transformers==4.51.3
      - peft==0.15.2
      - accelerate==1.6.0
      - datasets==3.5.0
      - huggingface-hub==0.30.2
      - numpy==1.26.4
      - scikit-learn==1.6.1
      - sentencepiece==0.2.0
      - safetensors==0.5.3
      - tqdm==4.67.1
